# WFC Quality Targets (generated by wfc-init)
.PHONY: quality-check format lint test test-build test-amd64 prod-build prod-smoke dev setup-dev dogfood preflight part-ui

quality-check: format lint
	@echo "All quality checks passed"

format:
	@echo "Formatting code..."
	@uv run black src/ tests/
	@echo "Code formatted"

lint:
	@echo "Linting..."
	@uv run ruff check src/ tests/
	@echo "Linting complete"

CONTAINER_ENGINE ?= $(shell command -v podman 2>/dev/null || command -v docker 2>/dev/null)
CONTAINER_COMMAND := $(notdir $(CONTAINER_ENGINE))
CONTAINER_RUN_SECURITY := $(if $(filter podman,$(CONTAINER_COMMAND)),--security-opt apparmor=unconfined,--security-opt seccomp=unconfined)
# Test image is multi-arch (Dockerfile.test FROM is a manifest-index digest), so the
# test platform defaults to the HOST arch: native arm64 on Apple Silicon (no qemu, no
# pyarrow segfault), native amd64 on the CI host. Override with TEST_PLATFORM=linux/amd64
# (or `make test-amd64`) for an explicit emulated CI-parity run.
HOST_ARCH := $(shell uname -m | sed -e 's/aarch64/arm64/' -e 's/x86_64/amd64/')
TEST_PLATFORM ?= linux/$(HOST_ARCH)
TEST_IMAGE ?= caliper-test:$(HOST_ARCH)
PROD_PLATFORM ?= linux/amd64
PROD_IMAGE ?= caliper:amd64

# All container builds route through scripts/build.sh + scripts/build-test.sh —
# they strip --security=insecure RUN directives for podman (unsupported on Mac)
# and set up the buildx insecure-entitlement builder for docker. Invoking
# podman/docker directly against Dockerfile/Dockerfile.test here would
# reintroduce that divergent, unstripped code path (#448).
test-build:
	@bash scripts/build-test.sh --build-only $(if $(filter linux/amd64,$(TEST_PLATFORM)),--amd64,--fast)

test:
	@bash scripts/build-test.sh $(if $(filter linux/amd64,$(TEST_PLATFORM)),--amd64,--fast)

# Explicit emulated CI-parity run (amd64 even on an arm64 host).
test-amd64:
	@bash scripts/build-test.sh --amd64

prod-build:
	@bash scripts/build.sh $(if $(filter linux/amd64,$(PROD_PLATFORM)),amd64,arm64)

prod-smoke: prod-build
	@$(CONTAINER_ENGINE) run --rm \
		--platform $(PROD_PLATFORM) \
		$(CONTAINER_RUN_SECURITY) \
		--entrypoint caliper \
		$(PROD_IMAGE) \
		--help >/dev/null

test-host:
	@CALIPER_ALLOW_HOST_TESTS=1 uv run pytest tests/ -v

test-e2e:
	@bash scripts/build.sh $(HOST_ARCH)
	@$(CONTAINER_ENGINE) run --rm \
		-v "$(CURDIR):/workspace:ro" \
		-w /workspace \
		-e CALIPER_E2E=1 \
		-e CALIPER_ALLOW_GLOBAL=1 \
		--entrypoint "" \
		caliper:latest \
		python3 -m pytest tests/e2e/ -v

test-all: test test-e2e

dev:
	@uv sync --group dev

setup-dev: dev
	@bash scripts/setup-dev.sh
	@bash scripts/install-hooks.sh

dogfood:
	bash scripts/dogfood.sh

preflight: quality-check test dogfood
	@echo "Preflight complete."

part-ui:
	bash scripts/build_part_ui.sh
